# Generated by Django 3.0.3 on 2020-02-29 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('title', models.CharField(max_length=30, verbose_name='Титул')),
                ('photo', models.ImageField(upload_to='sets', verbose_name='Фотографии')),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Тип товара',
                'verbose_name_plural': 'Типы товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=20, verbose_name='Титул')),
                ('description', models.TextField(max_length=150, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('active', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='products', verbose_name='Фотография')),
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='Слаг')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Collection')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.ProductType')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
            },
        ),
    ]
