# Generated by Django 3.0.3 on 2020-03-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=models.ImageField(upload_to='collections', verbose_name='Фотографии'),
        ),
    ]
