# Generated by Django 3.0.3 on 2020-03-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200302_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HumanGender',
        ),
    ]
