# Generated by Django 3.0.3 on 2020-03-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_humangender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humangender',
            options={'verbose_name': 'Гендер', 'verbose_name_plural': 'Гендер'},
        ),
        migrations.RemoveField(
            model_name='humangender',
            name='id',
        ),
        migrations.RemoveField(
            model_name='humangender',
            name='url',
        ),
        migrations.AddField(
            model_name='humangender',
            name='slug',
            field=models.SlugField(default=True, primary_key=True, serialize=False, unique=True, verbose_name='Слаг'),
        ),
    ]
