# Generated by Django 3.0.3 on 2020-03-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200303_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='products.HumanGender'),
        ),
    ]
